load("//config:rules.bzl", "application")

application(
    name = "Bizi",
    app_icons = [
        "//Bizi/Sources/Resources:AppIcon",
    ],
    infoplist = "Supporting Files/Info.plist",
    resources = [
        "//Bizi/Sources/Resources:Assets",
    ],
)
