config_setting(
    name = "develop",
    values = {
        "define": "environment=develop",
    },
    visibility = ["//visibility:public"],
)

config_setting(
    name = "staging",
    values = {
        "define": "environment=staging",
    },
    visibility = ["//visibility:public"],
)

config_setting(
    name = "production",
    values = {
        "define": "environment=production",
    },
    visibility = ["//visibility:public"],
)
